dataloader:
  kwargs:
    num_workers: 0
    shuffle: true
    train_batch_size: 1
    valid_batch_size: 1
  name: Dataloader
dataset:
  kwargs:
    data_dir: /dlbimg/datasets/View_transition/content_banjoman_480x270/vw_000
    frame_dims:
    - 270
    - 480
    frame_range:
    - 120
    - 134
  name: VideoDataset
iframe_net:
  ckpt_path: output/NIM/image_v0_s8/checkpoints/model_best.pth
  kwargs:
    delay_init: false
    hidden_layer_config:
    - 256
    - 256
    - 256
    in_channels: 2
    omega_0: 100
    omega_w: 100
    out_channels: 3
  name: SIREN
logger:
  kwargs:
    dummy_input: false
  name: ImageLogger
losses:
- name: MSELoss
  weight: 1.0
- name: L1Loss
  weight: 0.1
lr_scheduler:
  kwargs:
    gamma: 0.1
    step_size: 200
  name: StepLR
main:
  random_seed: '6666'
  saved_dir: output/NIM/video_v0_s8
metrics:
- name: PSNR
monitor:
  kwargs:
    early_stop: 0
    mode: min
    saved_freq: 10000000
    target: Loss
  name: Monitor
net:
  kwargs:
    delay_init: false
    hidden_layer_config:
    - 256
    - 256
    - 256
    in_channels: 3
    omega_0: 24
    omega_w: 24
    out_channels: 2
  name: SIREN
optimizer:
  kwargs:
    lr: 0.0001
  name: Adam
trainer:
  kwargs:
    device: cuda:0
    num_epochs: 320
    val_freq: 20
  name: VideoTrainer
