main:
    random_seed: '6666'
    saved_dir: 'output/NIM/banjo_vw02_ds'

dataset:
    name: 'ImageDataset'
    kwargs:
        path: '/dlbimg/datasets/View_transition/content_banjoman_480x270/vw_002/000.png'
        sidelen: [270, 480]
            
dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 1
        valid_batch_size: 1
        shuffle: false
        num_workers: 0

net:
    name: 'SIREN'
    kwargs:
        in_channels: 2
        out_channels: 3
        hidden_layer_config: [256, 256, 256]
        omega_0: 100
        omega_w: 100
        delay_init: false
        
losses:
    - name: 'MSELoss'
      weight: 1.0
    - name: 'L1Loss'
      weight: 0.1

metrics:
    - name: 'PSNR'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.0001

lr_scheduler:
    name: StepLR
    kwargs:
        step_size: 1200
        gamma: 0.1

logger:
    name: 'ImageLogger'
    kwargs:
        dummy_input: false

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 10000000
        early_stop: 0

trainer:
    name: 'ImageTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 1600
        val_freq: 50
