main:
    random_seed: '6666'
    saved_dir: 'output/NIM/banjo_v00_v02'

dataset:
    name: 'WarpingDataset'
    src_kpts_path: data/banjo_00_02/1024/000_v0.dat
    tgt_kpts_path: data/banjo_00_02/1024/000_v2.dat
    kwargs:
        time_range: [-1.0, 1.0]
        n_samples: 20000
            
dataloader:
    name: 'Dataloader'
    kwargs:
        train_batch_size: 1
        valid_batch_size: 1
        shuffle: true
        num_workers: 0

im_net:
    src_ckpt_path: output/NIM/banjo_v00/checkpoints/model_best.pth
    tgt_ckpt_path: output/NIM/banjo_v02/checkpoints/model_best.pth
    name: 'SIREN'
    kwargs:
        in_channels: 2
        out_channels: 3
        hidden_layer_config: [256, 256, 256]
        omega_0: 100
        omega_w: 100
        delay_init: false


net:
    name: 'SIREN'
    kwargs:
        in_channels: 3
        out_channels: 2
        hidden_layer_config: [128, 128]
        omega_0: 24
        omega_w: 24
        delay_init: false
        
losses:
    constraint_weights:
        data_constraint:  10000
        identity_constraint:  1000
        inv_constraint: 10000
        TPS_constraint: 1000
    intermediate_times: [0.16, 0.32, 0.5, 0.66, 0.82]
    
metrics:
    - name: 'PSNR'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.0001

lr_scheduler:
    name: StepLR
    kwargs:
        step_size: 100000
        gamma: 0.95

logger:
    name: 'WarpingLogger'
    kwargs:
        dummy_input: false

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'Loss'
        saved_freq: 10000000
        early_stop: 0

trainer:
    name: 'WarpingTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 10001
        ckpt_step: 5000
        vis_step: 1000
        n_samples: 20000
        warmup_steps: 1000
        frame_dim: [540, 960]
        n_frames: 101
        fps: 20
        
        
       
